version: "3.8"
services:
  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=pulse
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=pulse
    volumes:
      - 'pulse_db:/var/lib/postgresql/data'
    networks:
      - pulse-network

networks:
  pulse-network:
volumes:
  pulse_db:
